module.exports = {
  mySidebar: [
    'overview',
    'release-notes',
    {
      type: 'category',
      label: 'Installation',
      collapsed: true,
      link: { type: 'doc', id: 'installation/overview' },
      items: [
        'installation/checklist',
        'installation/process',
        'installation/verifying',
      ],
    },
    'customization',
    'operations',
    {
      type: 'category',
      label: 'Advanced features',
      collapsed: true,
      link: { type: 'doc', id: 'advanced-features/overview' },
      items: [
        'advanced-features/csa-storage',
        'advanced-features/xpscomm',
        'advanced-features/ispf',
        'advanced-features/mapping',
        'advanced-features/xpstimer',
        'advanced-features/xpstrack',
        'advanced-features/xpswto',
        'advanced-features/xpswtor',
        'advanced-features/xprlist',
        'advanced-features/restarting-jobs',
        'advanced-features/xpuser01',
      ],
    },
    'machine-messages',
    {
      type: 'category',
      label: 'Reference',
      collapsed: true,
      link: { type: 'doc', id: 'reference/overview' },
      items: [
        'reference/saf-resources',
        'reference/multiple-lsams',
        'reference/standalone-file-transfer',
        'reference/djf',
        'reference/translation-tables',
        'reference/tls',
        'reference/faq',
        'reference/known-issues',
      ],
    },
  ],
};
